apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerodowntime-v2
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerodowntime
      version: v2
  template:
    metadata:
      labels:
        app: zerodowntime
        version: v2
    spec:
      containers:
      - name: zerodowntime
        image: docker.io/gortazar/flyway:v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9991
        env:
        - name: MYSQL_HOST
          value: "db-flyway"
        - name: SERVER_PORT
          value: "9991"
        - name: SPRING_FLYWAY_VALIDATE-ON-MIGRATE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: zerodowntime
  labels:
    app: zerodowntime
spec:
  ports:
  - port: 9991
    name: http
  selector:
    app: zerodowntime
